version: '3.9'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    environment:
      - SECRET_KEY=devsecret
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRESS_USER=devuser
      - POSTGRESS_PASSWORD=changeme