version: '3.9'
#  python manage.py sync_data_to_db &&
services:
  backend:
    build: 
      context: ./backend
    container_name: backend
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
            
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    environment:
      - SECRET_KEY=devsecret
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    stdin_open: true
    tty: true

  db:
    image: postgres:13-alpine
    container_name: postgres_database
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme