# Generated by Django 4.2.10 on 2024-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year_founded',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
